steps:
- name: 'gcr.io/$PROJECT_ID/git'
  args: ['clone', 'https://github.com/Pudirohith/game.git']
steps:
 - name: maven:3-jdk-8
   entrypoint: mvn
   args: ['install']
steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/fluent-service-325915/game-of-life:v1', '--build-arg=JAR_FILE=target/', '.']
images: ['gcr.io/fluent-service-325915/game-of-life:v1']
