steps:
- name: 'gcr.io/$PROJECT_ID/git'
  args: ['clone', 'https://github.com/Pudirohith/game.git']
steps:
# build the Java app and package it into a jar
- name: maven:3-jdk-8
  entrypoint: mvn
  args: ["package", "-Dmaven.test.skip=true"]
