steps:
- name: maven:3-jdk-8
  entrypoint: mvn
  args: ["package", "-Dmaven.test.skip=true"]
- name: gcr.io/cloud-builders/docker
  args: ["build", "-t", "gcr.io/$PROJECT_ID/game-of-life", "--build-arg=JAR_FILE=target/game-of-life-1.0-SNAPSHOT.jar", "."]
